# Generated by Django 5.2.2 on 2025-11-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agen_kapal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(blank=True, max_length=100, null=True)),
                ('detail_layanan', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Buka'), ('2', 'Penuh'), ('3', 'Tutup')], default='1')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diedit_pada', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
