# Generated by Django 5.2.8 on 2025-11-27 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agen_kapal', '0003_karyawan_detail_karyawan_karyawan_no_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='status',
            field=models.CharField(choices=[('1', 'On'), ('2', 'Off')], default='1'),
        ),
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_foto', models.FileField(blank=True, null=True, upload_to='berkas_absen/')),
                ('keterangan', models.TextField()),
                ('status', models.CharField(choices=[('1', 'Hadir'), ('2', 'Izin'), ('3', 'Sakit'), ('4', 'Alpha')], default='1')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agen_kapal.karyawan')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField()),
                ('diedit_pada', models.DateTimeField(auto_now=True)),
                ('diedit_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agen_kapal.karyawan')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agen_kapal.request')),
            ],
        ),
        migrations.DeleteModel(
            name='Kehadiran',
        ),
    ]
