# Generated by Django 5.2.8 on 2025-11-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agen_kapal', '0004_karyawan_status_absen_todolist_delete_kehadiran'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe_histori', models.CharField(blank=True, max_length=50, null=True)),
                ('detail_histori', models.TextField()),
            ],
        ),
    ]
