# Generated by Django 5.2.8 on 2025-11-27 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agen_kapal', '0005_histori'),
    ]

    operations = [
        migrations.AddField(
            model_name='histori',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 11, 27, 6, 14, 49, 391060, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
