# Generated by Django 5.2.8 on 2025-11-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agen_kapal', '0006_histori_dibuat_pada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='histori',
            name='dibuat_pada',
        ),
    ]
